version: "3.8"

services:
  # custom image
  app:
    build:
      args:
        user: miqueias
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: miqueiasjed/api-ead
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    depends_on:
      - pgsql
    networks:
      - docker-laravel

  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  # db
  pgsql:
    image: postgres:latest
    platform: linux/x86_64
    container_name: pgsql-db
    restart: unless-stopped
    ports:
        - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
     - ./.docker-bd/postgres:/var/lib/postgresql/data
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge
